name: reusable_testing

on:
  workflow_call:
    inputs:
      artifact_name:
        description: The name of the tarantool build artifact
        default: ubuntu-focal
        required: false
        type: string

jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone the tarantool-c connector
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository_owner }}/tarantool-c
          # Enable recursive submodules checkout as test-run git module is used
          # for running tests.
          submodules: recursive

      - name: Download the tarantool build artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.artifact_name }}

      - name: Install tarantool
        # Now we're lucky: all dependencies are already installed. Check package
        # dependencies when migrating to other OS version.
        run: sudo dpkg -i tarantool*.deb

      - name: Setup python3 for tests
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install test requirements
        run: pip install -r test-run/requirements.txt

      - run: cmake . && make
      - run: ulimit -n 8192 # set file descriptors limit to enable poll test
      - run: make test
